<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <!-- ASP.NET Core shared framework: DI, logging, options, HTTP abstractions. -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="EFCore.NamingConventions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiniBanking.SharedKernel\MiniBanking.SharedKernel.csproj" />
  </ItemGroup>

</Project>
